### ISSUE TITLE
Contributor guide??

### ISSUE THREAD

**Issue by Xhanti** [blogifierdotnet/Blogifier#166]
Hi,

I'm starting out setting up a blog and saw this project and am very impressed.
I wanted to know if there is contributor guide or issues that are up for grabs that someone could take on and run with?

Regards

**Comment by rxtur** [comment]
I'll add contributor guide to docs, but it shouldn't be much different from any generic "how to contribute to Github" walk through. Few specifics yes, but hopefully not much. Issues are here in this list, I think currently it is just good to haves no real bugs.

**Comment by Farrell23** [comment]
@xhanti Hi, I was also impressed with the project and I am turning it down for myself as well. As a personal blog on the .net platform and related topics. I wanted to make a tutorial in order to facilitate the study for beginners in the future, but I don’t know how to react @rxtur

**Comment by rxtur** [comment]
Well for starters here are few things from the top of my head, without given it too much thought. Will build on it later on.

Project should be small enough for single developer to handle, but provide extension points for anyone who needs something outside core functionality. That means, before start on any code - lets discuss where it should go. Core project? Plugin? I can help with that.

One area I don't have time for yet is localization on theme level. There is JSON resource file used by admin via back-end code, same file should be used in JavaScript so that theme author can use localized strings instead of hard-coded values.

Also for the core project, want to add ability to set post as a "page". So that is won't show up in the post lists but will be available in the "/pages/page-slug".

Menus - admin needs a way to create a "menu" - container for posts or pages. That container should be exposed via API and, inside theme, author could add dynamic menus pulling items from that API. So blogger could go to admin, create new post or page, add to existing menu and it would pop up in the blog.

And if you want to do none-coding contribution, like write a tutorial or do a video or whatever - that would be great! Let me know and I'll add a link to the project so it will be beneficial for all parties.
