### ISSUE TITLE
Unable to Save and Publish Blogs

### ISSUE THREAD

**Issue by vinodkondabathula** [blogifierdotnet/Blogifier#216]
### Unable to save  and publish blogs.
![Capture](https://user-images.githubusercontent.com/64190843/95950513-4da82f00-0e12-11eb-9e0c-0477ad8f2149.PNG)

**Comment by rxtur** [comment]
This error usually happens when application expects JSON from API but instead getting error page that starts with angle bracket. Could be because you running in IIS in the subfolder, like `localhost/myapp/blog` etc. I'm going to look into this scenario and submit a fix this weekend.

Update: the fix is in, give it a try.

**Comment by vinodkondabathula** [comment]
> This error usually happens when application expects JSON from API but instead getting error page that starts with angle bracket. Could be because you running in IIS in the subfolder, like `localhost/myapp/blog` etc. I'm going to look into this scenario and submit a fix this weekend.
> 
> Update: the fix is in, give it a try.

Above fix didn't work. Attaching the error log from dev console. 
[localhost-1602912134787.log](https://github.com/blogifierdotnet/Blogifier/files/5395028/localhost-1602912134787.log)

I am not running the application in the subfolder. I can reproduce this bug in debugging as well.

**Comment by rxtur** [comment]
Fixed with latest update.
