### ISSUE TITLE
Additional setting for a wide logo, and use the uploaded logos in the themes

### ISSUE THREAD

**Issue by mawarnes** [blogifierdotnet/Blogifier#229]
Hi, first of all fantastic application, I absolutely love it.

Could I submit a PR to add a second 'wide' logo image in the settings which will get used in the themes. So for example the wide logo would be good for the View theme, and the existing logo setting could be used in the standard theme.

If you think it might be a good idea, or at least to use the logo in the settings in the theme I can submit a PR

Do you prefer to have PRs submitted to dev or master?

**Comment by rxtur** [comment]
You may first check with [Farzin](https://github.com/farzindev) who works on UX for a new version to make sure it fits with design overall. If that's fine, best would be submit to dev - it has all the new code and features and master would need to be merged manually so some things can get lost in transition or not even relevant because things changed a lot.

**Comment by farzindev** [comment]
Hi @mawarnes,

One user wants a wider logo or two logos on the header and footer.
Another user wants the title of the blog on the header only.

So because the Logo and Cover are related to the design(themes),
We removed those fields from the blog settings.

Instead, now we have theme settings.
Theme developers now are able to add any custom fields to the theme,
And give users as many options as they want.

Also, we are working on a new Standard theme for the Blogifier 3.0

**Comment by mawarnes** [comment]
ahh yes I see the changes in the dev branch, excellent work, that's a much better approach great information, and many thanks. Please keep up the excellent work.
